### PR TITLE
chore: Add benchmark for shortening embedding

### PR DESCRIPTION
**Pull request by gaocegege**
- Update the blog post link in readme
- Add new benchmark data

### CODE REVIEW

**Comment by VoVAllen** [comment]
Can you draw a chart here? It's hard to read the table actually

**Comment by gaocegege** [comment]
image

**Comment by VoVAllen** [comment]
KNN -> ANN

And can you include a sample SQL or the repo so that user can see how that can be done?

**Comment by gaocegege** [comment]
I think it should be in the blog post instead of the benchmark doc, WDYT

**Comment by VoVAllen** [comment]
Fine to in the blog. We can add the link to blog later

**Comment by gaocegege** [comment]
Comments are addressed, please take a look.
Thanks for your time :smile:

**Pull request merged**
